### ISSUE TITLE
Compilation error: reference to ‘utils’ is ambiguous

### ISSUE THREAD

**Issue by manpan-1** [dicengine/dice#145]
I am trying to build on openSUSE Leap 15.1 and I get the following error.
```
Scanning dependencies of target DICe_TrackingMovieMaker
[ 38%] Building CXX object tools/CMakeFiles/DICe_TrackingMovieMaker.dir/DICe_TrackingMovieMaker.cpp.o                                                                        
/home/fsol/Programs/dice/tools/DICe_TrackingMovieMaker.cpp: In function ‘int main(int, char**)’:                                                                             
/home/fsol/Programs/dice/tools/DICe_TrackingMovieMaker.cpp:272:19: error: reference to ‘utils’ is ambiguous                                                                  
     Mat mat_img = utils::read_image(cine_ss.str().c_str());
                   ^~~~~
In file included from /home/fsol/Programs/dice/tools/DICe_TrackingMovieMaker.cpp:48:0:
/home/fsol/Programs/dice/src/utils/src/DICe_ImageIO.h:65:11: note: candidates are: namespace DICe::utils { }                                                                 
 namespace utils{
           ^~~~~
In file included from /usr/include/opencv2/core.hpp:3276:0,
                 from /usr/include/opencv2/core/core.hpp:48,
                 from /home/fsol/Programs/dice/src/utils/src/DICe_ImageIO.h:52,
                 from /home/fsol/Programs/dice/tools/DICe_TrackingMovieMaker.cpp:48:
/usr/include/opencv2/core/utility.hpp:1227:11: note:                 namespace cv::utils { }                                                                                 
 namespace utils {
           ^~~~~
make[2]: *** [tools/CMakeFiles/DICe_TrackingMovieMaker.dir/build.make:63: tools/CMakeFiles/DICe_TrackingMovieMaker.dir/DICe_TrackingMovieMaker.cpp.o] Error 1                
make[1]: *** [CMakeFiles/Makefile2:455: tools/CMakeFiles/DICe_TrackingMovieMaker.dir/all] Error 2                                                                            
make: *** [Makefile:130: all] Error 2
```
Here is my do-cmake

```
#!/bin/bash

EXTRA_ARGS=$@

rm -f CMakeCache.txt
rm -rf CMakeFiles

cmake \
 -D CMAKE_BUILD_TYPE=RELEASE \
 -D DICE_TRILINOS_DIR=/opt/Trilinos12/ \
 -D CMAKE_INSTALL_PREFIX:FILEPATH=/opt/DICe/ \
 -D CMAKE_VERBOSE_MAKEFILE:BOOL=ON \
 -D DICE_DEBUG_MSG:BOOL=OFF \
 -D DICE_USE_DOUBLE:BOOL=OFF \
 -D TIFF_DIR:FILE_PATH="/usr/lib64/" \
 -D JPEG_DIR:FILE_PATH="/usr/lib64/" \
 -D PNG_DIR:FILE_PATH="/usr/lib64/" \
 -D CMAKE_CXX_FLAGS:STRING="-Wall" \
 $EXTRA_ARGS ../

```
I have built the Trilinos with the required packages and OpenBLAS 0.3.6. I got opencv 3.3.1-lp151.5.5 and the devel files from the opensuse main repository. I attach my CMake logfile.
[CMakeOutput.log](https://github.com/dicengine/dice/files/3722507/CMakeOutput.log)

**Comment by manpan-1** [comment]
I also tried with opencv 4.1.1, still the same error. Only this time the on a different line:
`/usr/include/opencv2/core/utility.hpp:1310:11: note:                 namespace cv::utils { }`

**Comment by dicengine** [comment]
Which version of opencv were you building against in the first attempt?

On Oct 13, 2019, at 4:26 PM, Panagiotis Manoleas <notifications@github.com<mailto:notifications@github.com>> wrote:


I also tried with opencv 4.1.1, still the same error. Only this time the on a different line:
/usr/include/opencv2/core/utility.hpp:1310:11: note: namespace cv::utils { }

**Comment by manpan-1** [comment]
I had opencv 3.3.1 the first time... and the corresponding devel files of the same version.

**Comment by dicengine** [comment]
The tests we have are using OpenCV 3.2.0. I would try to build with that version and see if the build error persists.

On Oct 15, 2019, at 3:26 AM, Panagiotis Manoleas <notifications@github.com<mailto:notifications@github.com>> wrote:


I had opencv 3.3.1 the first time... and the corresponding devel files of the same version.

**Comment by manpan-1** [comment]
Yes, that's what I thought as well. I'll try out

**Comment by manpan-1** [comment]
Well, it worked with opencv 3.2.0 after all. I had some issues building opencv ([this helped](https://stackoverflow.com/questions/46884682/error-in-building-opencv-with-ffmpeg)) but in the end, it works.
I would suggest editing requirements in "Getting Started" to mention that the specific version of opencv is needed until it is patched (it says "opencv 3.2.0 or greater). Shall I leave this issue open till then?

**Comment by dicengine** [comment]
Glad it works now. I will update the instructions. You’re right about this. I’ll close the issue when I’ve done this. Thanks



On Oct 15, 2019, at 4:01 PM, Panagiotis Manoleas <notifications@github.com<mailto:notifications@github.com>> wrote:


Well, it worked with opencv 3.2.0 after all. I had some issues building opencv (this helped<https://stackoverflow.com/questions/46884682/error-in-building-opencv-with-ffmpeg>) but in the end, it works.
I would suggest editing requirements in "Getting Started" to mention that the specific version of opencv is needed until it is patched (it says "opencv 3.2.0 or greater). Shall I leave this issue open till then?

**Comment by dicengine** [comment]
I just made a local commit that makes the build docs more clear. I'll go ahead and close this issue.
