### ISSUE TITLE
Build/Install instructions don't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by bbellster** [dicengine/dice#177]
First, let me say that I am not a software engineer, so some of what I may say here may be naiive or just wrong. Also, the only reason that I am build this is to have debugging available so that I can understand a stereo calibration issue (see  [here](https://github.com/dicengine/dice/issues/174) if interested.

I am dealing with a host of errors. I'll try to explain everything that I tried.
1. Trilinos would not build because of this error:
 seacas/libraries/ioss/src/Ioss_CodeTypes.h:71:10: fatal error: Kokkos_Core.hpp: No such file or directory
2. I disabled ioss in the do-trilinos-cmake script like this:
-D Trilinos_ENABLE_SEACASIoss:BOOL=OFF \
3. Trilinos then complied and installed correctly (I think)
4. Now dice still has the following build error:
trilinos-12.4.2-Source/build/install/lib/libexodus.a(ex_utils.c.o): undefined reference to symbol 'H5get_libversion@@HDF5_SERIAL_1.8.7'

I have no idea where to go from here... any help would be appreciated.

**Comment by dicengine** [comment]
If you change the calibration image folder to one without any non-alphabetic or numeric characters, the calibration tool should work. (I made a similar comment to the issue reference above).

If you still want to build DICe to get debugging output, I would suggest not using Ubuntu since there are some complications for building the dependency libraries on Ubuntu. If you do decide to keep using Ubuntu, you will need to build Trilinos with SECASIoss on becuase it's required. DICe won't build with this turned off since it uses the Exodus file output format which requires SEACAS to be on.
